# Generated by Django 5.2.8 on 2025-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ItmID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('MerchID', models.CharField(max_length=7)),
                ('Cost', models.FloatField()),
                ('WarrantyTime', models.IntegerField()),
                ('Ratings', models.FloatField()),
                ('DelvDate', models.DateField()),
            ],
        ),
    ]
